default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: task_runner_development

test:
  <<: *default
  database: task_runner_test

production:
  <<: *default
  database: task_runner_production
